---
- hosts: localhost
  become: true
  handlers:
    - import_tasks: playbooks/common/handlers.yaml

  tasks:

    - block:
        - include_vars: secrets/passwords.yaml
      tags:
        - always

    - include_tasks: playbooks/security.yaml
    - include_tasks: playbooks/baseline.yaml
