---

- name: restart crowdsec
  service:
    name: crowdsec
    state: restarted
    enabled: true

- name: restart crowdsec bouncer
  service:
    name: crowdsec-firewall-bouncer-nftables
    state: restarted
    enabled: true
