---
- name: systemd daemon-reload
  systemd:
    daemon_reload: yes

- name: restart crowdsec
  service:
    name: crowdsec
    state: restarted
    enabled: true

- name: restart chronyd
  service:
    name: chronyd
    state: restarted
    enabled: true

- name: restart crowdsec bouncer
  service:
    name: crowdsec-firewall-bouncer
    state: restarted
    enabled: true
