---

##
# Toggle functionality
#
configure_dns:            True
configure_ntp:            True
configure_updates:        True
configure_proxy:          True
configure_systemd_proxy:  True
configure_baseline_proxy: True
configure_baseline:       True
configure_security:       True


##
# Proxy
# proxy.dmz.sigaint.au
#
proxy_server: proxy.dmz.sigaint.au
proxy_server_port: 3128
no_proxy: "10.120.0.0/16"

##
# NTP Servers
#
ntp_servers:
  - time1.google.com
  - time2.google.com
  - time2.google.com

##
# DNS Search
#
dns_search:
  - sigaint.au

##
# DNS Servers
#
dns_servers:
  - 10.120.2.1
