---

##
# Toggle functionality
#
configure_dns:      "{{ (True if 'au.hahl.baseline.role-dns'      in metadata_service.keys()) | default(True) }}"
configure_ntp:      "{{ (True if 'au.hahl.baseline.role-ntp'      in metadata_service.keys()) | default(True) }}"
configure_updates:  "{{ (True if 'au.hahl.baseline.role-updates'  in metadata_service.keys()) | default(True) }}"
configure_proxy:    "{{ (True if 'au.hahl.baseline.role-proxy'    in metadata_service.keys()) | default(True) }}"
configure_baseline: "{{ (True if 'au.hahl.baseline.role-baseline' in metadata_service.keys()) | default(True) }}"
configure_crowdsec: "{{ (True if 'au.hahl.baseline.role-crowdsec' in metadata_service.keys()) | default(False)}}"
configure_security: "{{ (True if 'au.hahl.baseline.role-security' in metadata_service.keys()) | default(True) }}"


##
# Proxy
# syd-proxy-vip.dmz.hahl.id.au
# - No proxy fo OpenStack, and Metadata Service.
#
proxy_server: 172.16.17.38
proxy_server_port: 3128
no_proxy: "172.16.17.0/24, 10.0.120.126, 169.254.169.254"

# Crowdsec configuration.
#
crowdsec_collections:
  - crowdsecurity/linux
  - crowdsecurity/haproxy
  - crowdsecurity/whitelist-good-actors

##
# NTP Servers
#
ntp_servers:
  - syd-proxy-01.dmz.hahl.id.au
  - syd-proxy-02.dmz.hahl.id.au

##
# DNS Servers
#
dns_servers:
  - 172.16.17.36 # syd-proxy-01
  - 172.16.17.37 # syd-proxy-02
