---

- name: crowdsec | install
  block:

  - name: crowdsec | install yum repo
    template:
      src: "../templates/crowdsec/crowdsec.repo.j2"
      dest: "/etc/yum.repos.d/crowdsec.repo"
      mode: "0755"
      owner: "root"
      group: "root"

  - name: crowdsec | install agent package
    package:
      name:
        - crowdsec
        - crowdsec-firewall-bouncer-nftables
      state: installed 
    notify:
      - restart crowdsec
      - restart crowdsec bouncer

  - name: crowdsec | create systemd dropin directory
    file:
      path: /etc/systemd/system/crowdsec.service.d
      state: directory
      mode: "0755"
    notify:
      - restart crowdsec
      - restart crowdsec bouncer

  - name: crowdsec | install agent configuration
    template:
      src: "../templates/crowdsec/acquis.yaml.j2"
      dest: "/etc/crowdsec/acquis.yaml"
      mode: "0755"
      owner: "root"
      group: "root"
    notify:
      - restart crowdsec
      - restart crowdsec bouncer
      

  tags:
    - crowdsec
    - crowdsec:install

- name: crowdsec | configuraion
  block:
    - name: crowdsec | get installed collections
      command: "/bin/cscli collections list"
      register: cscli_cmd
      changed_when: false

    - name: crowdsec | install collections
      command: "/bin/cscli collections install {{item}}"
      with_items: "{{crowdsec_collections}}"
      when: item not in cscli_cmd.stdout
      notify: restart crowdsec

  tags:
    - crowdsec
    - crowdsec:configure
