---

- name: dns | configure dns servers
  block:

  - name: dns | configure nameservers
    template:
      src: "../templates/dns/resolv.conf.j2"
      dest: "/etc/resolv.conf"
      mode: "0755"
      owner: "root"
      group: "root"
    tags:
      - dns
      - dns:configure
  tags:
    - dns
