---

- name: idmapd | configure idmapd
  block:

  - name: idmapd | get system dns domain
    shell: "hostname -d"
    register: hostname_out

  - name: idmapd | configure idmapd
    template:
      src: "../templates/idmapd/idmapd.conf.j2"
      dest: "/etc/idmapd.conf"
      mode: "0755"
      owner: "root"
      group: "root"
    tags:
      - idmapd
      - idmapd:configure
  tags:
    - idmapd
