---

- name: idmapd | configure idmapd
  block:

  - name: idmapd | get system dns domain
    shell: "hostname -d"
    register: hostname_out
    tags:
      - idmapd
      - idmapd:configure

  - name: idmapd | configure idmapd
    template:
      src: "../templates/idmapd/idmapd.conf.j2"
      dest: "/etc/idmapd.conf"
      mode: "0755"
      owner: "root"
      group: "root"
    register: idmapd
    tags:
      - idmapd
      - idmapd:configure

  - name: idmapd | clear cache
    shell: "nfsidmap -c"
    when: idmapd.changed
    tags:
      - idmapd
      - idmapd:configure
      - idmapd:clear_cache

  tags:
    - idmapd
