---

- name: install | ensure system automatically appliess baseline
  block:

    - name: install | create systemd service
      template:
        src:  ../templates/baseline/baseline.service.j2
        dest: /etc/systemd/system/baseline.service

    - name: install | create systemd timer
      template:
        src:  ../templates/baseline/baseline.timer.j2
        dest: /etc/systemd/system/baseline.timer

    - name: install | enable timer
      systemd:
        daemon_reload: true
        name: baseline.timer
        enabled: true

  tags:
    - install
    - install:baseline
