---

- name: security | apply security hardening
  block:
  - name: security | create motd directory
    file:
      dest: /etc/motd.d
      state: directory
      

  - name: security | remove motd
    shell: "rm /etc/motd.d/{cockpit,insights-client} || true"
    changed_when: false

  - name: security | deploy motd
    copy:
      dest: "/etc/motd.d/hahl"
      content: |+

          sSSs   .S    sSSSSs   .S_SSSs     .S   .S_sSSs    sdSS_SSSSSSbs  
         d%%SP  .SS   d%%%%SP  .SS~SSSSS   .SS  .SS~YS%%b   YSSS~S%SSSSSP  
        d%S'    S%S  d%S'      S%S   SSSS  S%S  S%S   `S%b       S%S       
        S%|     S%S  S%S       S%S    S%S  S%S  S%S    S%S       S%S       
        S&S     S&S  S&S       S%S SSSS%S  S&S  S%S    S&S       S&S       
        Y&Ss    S&S  S&S       S&S  SSS%S  S&S  S&S    S&S       S&S       
        `S&&S   S&S  S&S       S&S    S&S  S&S  S&S    S&S       S&S       
          `S*S  S&S  S&S sSSs  S&S    S&S  S&S  S&S    S&S       S&S       
           l*S  S*S  S*b `S%%  S*S    S&S  S*S  S*S    S*S       S*S       
          .S*P  S*S  S*S   S%  S*S    S*S  S*S  S*S    S*S       S*S       
        sSS*S   S*S   SS_sSSS  S*S    S*S  S*S  S*S    S*S       S*S       
        YSS'    S*S    Y~YSSY  SSS    S*S  S*S  S*S    SSS       S*S       
                SP                    SP   SP   SP               SP        
                Y                     Y    Y    Y                Y         

  - name: security | add profile changes
    template:
      src: "../templates/security/99-security.sh.j2"
      dest: "/etc/profile.d/99-security.sh"
      mode: "0755"
      owner: "root"
      group: "root"

  tags:
    - security
