---

- name: security | set timezone to Australia/Sydney
  timezone:
    name: Australia/Sydney

- name: security | apply security hardening
  block:
  - name: security | create motd directory
    file:
      dest: /etc/motd.d
      state: directory
      

  - name: security | remove motd
    shell: "rm /etc/motd.d/{cockpit,insights-client} || true"
    changed_when: false

  - name: security | deploy motd
    copy:
      dest: "/etc/motd.d/sigaint"
      content: |+
       $
                       __
                      / _)
             _.----._/ /
            /         /
         __/ (  | (  | It's a UNIX System!
        /__.-'|_|--|_|    I know this!  

  - name: security | add profile changes
    template:
      src: "../templates/security/99-security.sh.j2"
      dest: "/etc/profile.d/99-security.sh"
      mode: "0755"
      owner: "root"
      group: "root"

  tags:
    - security

